format = """
[{](bright-blue) $container ${custom.system_icons}$username$hostname:$directory[}](bright-blue)$git_branch$git_state$git_status$git_commit$python$ruby$rust$terraform
$character
"""

add_newline = false
scan_timeout = 10
continuation_prompt = "[âˆ™âˆ™âˆ™](bright-black) "

[fill]
symbol = " "

[character]
format = "$symbol "
success_symbol = "[%](bright-yellow)"
error_symbol = "[%](bright-red)"

[username]
format = "[$user](yellow)[@](blue)"
show_always = true

[hostname]
format = "[$ssh_symbol$hostname]($style)"
ssh_symbol = "ğŸŒ "
ssh_only = false

[container]
format = "[$symbol]($style)"
style = "yellow"

[time]
format = '[$time](dimmed bright-red)'
utc_time_offset = "-4"
time_format = "%T"
disabled = false
time_range = "-"

[directory]
read_only = "ï ½"
truncation_symbol = "â€¦/"
truncate_to_repo = false
truncation_length = 100

[terraform]
format = "[$symbol$workspace]($style) "

[git_branch]
symbol = "îœ¥ "
format = " [$symbol$branch]($style) "

[golang]
symbol = "î˜§ "

[hg_branch]
symbol = "îœ¥ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "
format = '[$symbol$state( \($name\))]($style) '

[package]
symbol = "ï£– "

[perl]
symbol = "î© "

[php]
symbol = "î˜ˆ "

[python]
symbol = "ï Ÿ "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[ruby]
symbol = "îˆ¾ "
format = "[$symbol($version )]($style)"

[rust]
symbol = "î¨ "
format = "[$symbol($version )]($style)"


[swift]
symbol = "ï¯£ "

[custom.system_icons]
description = "Show system icons"
command     = 'echo $STARSHIP_OS_ICON'
#command     = '([ $(uname -s) == "Darwin" ] && echo ï…¹) || ([ $(uname -s) == "Linux" ] && echo ïŒš)'
format      = "[$output]($style) "
style       = "bold bright-yellow"
shell       = ["bash", "--noprofile", "--norc"]
when        = "true"
